version: '3.3'
volumes:
  data:
services:
  blog:
    image: mysql:5.6
    ports:
      - "3306:3306"
    volumes:
      - data:/var/lib/mysql
    environment:
      - MYSQL_DATABASE=blog
  app:
    image: phpmyadmin/phpmyadmin:latest
    links:
      - blog
    ports:
      - 80:80
    environment:
      - PMA_ARBITRARY=1